name: native_view
description: A QR CODE Flutter plugin (Web only).
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  native_view_platform_interface:
    path: plugin/native_view_platform_interface/
  native_view_web:
    path: plugin/native_view_web/

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  plugin_platform_interface: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        default_package: native_view_web
